version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gider_takip_db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    restart: always

  app:
    build: .
    container_name: python_app
    depends_on:
      - db
    volumes:
      - .:/app
    # Etkileşimli (input olan) Python uygulamalarının Docker üzerinde çalışabilmesi için terminal tanımları:
    stdin_open: true # docker run -i
    tty: true        # docker run -t

volumes:
  mysql_data:
